### ISSUE TITLE
create progress bar for every video

### ISSUE THREAD

**Issue by melbehiry** [nihk/exo-viewpager-fun#10]
this is a perfect example, could you please give a hint or instruction on the best way if I want to add a linear progress bar within every screen, with the MVI? 
thanks :)

**Comment by nihk** [comment]
hey @Elbehiry. for the UI itself, ExoPlayer's PlayerControlView implementation provides some insight into this. it listens to Player [events](https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerControlView.java#L1304) and also [polls](https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerControlView.java#L1054-L1063) around once per second to get nearly real-time player timeline data, which gets set on a `TimeBar` (effectively a SeekBar). you could do the same thing and read the player's content data on each callback, such as content duration and position, and feed it into your own [SeekBar](https://developer.android.com/reference/android/widget/SeekBar) to set its progress. (this repo deliberately avoids references to ExoPlayer APIs outside the `:exo` and `:app` modules, which is why there is a need (and preference) to use SeekBar and not TimeBar in the `:videopager` module.)

similarly, a user's interaction with SeekBar fires callbacks; in those you could set the AppPlayer instance's content position, based on what percentage of the SeekBar's total progress it was scrubbed to.

regarding MVI, your `AppPlayer` instance could expose a `Flow` which emits a data class that owns things like content position/duration. those data class instances would be created within and emitted from the timeline data callbacks on ExoPlayer described at the start of this comment. the same place where other AppPlayer streams are listened to would be a good place to add this new stream of content position/duration data, i.e. [here](https://github.com/nihk/videopager/blob/main/videopager/src/main/kotlin/com/videopager/vm/VideoPagerViewModel.kt#L111-L115). those emissions can ultimately be written to the `ViewState` in the MVI reducer.
